/**
 * kb/generate.ts — suggested KB article generation.
 *
 * Turns a resolved support interaction (customer question + what the specialists
 * found/did + the final resolution) into a clean, reusable knowledge-base
 * article DRAFT. The draft is NEVER saved automatically — it's returned for an
 * admin to review and edit, then persist through the normal KB store.
 *
 * Primary path: the shared LLM gateway. Fallback (offline / failure): a
 * deterministic template assembled from the same source material, so the feature
 * always produces something usable.
 */
import { callLLM, availableProviders } from "../gateway/index";
import { log } from "../core/logger";
import { GUARDRAILS_BLOCK } from "../core/guardrails";
import { listKbDocs } from "./store";

export interface KbSource {
  /** The customer's question(s) / problem in their words. */
  question?: string;
  /** The merged resolution summary the engine produced. */
  resolution?: string;
  /** Concrete findings discovered while investigating. */
  findings?: string[];
  /** Concrete actions taken / recommended. */
  actions?: string[];
  /** Domain/intent (e.g. "billing", "orders") to flavor the article. */
  domain?: string;
  /** Optional extra free-text context (transcript snippets, etc). */
  notes?: string;
}

export interface KbDraft {
  title: string;
  filename: string;
  content: string;
  summary: string;
  /** "llm" when generated by the model, "template" for the deterministic path. */
  source: "llm" | "template";
}

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 48) || "article"
  );
}

/** Ensure the suggested filename is unique against the current library. */
function uniqueFilename(base: string): string {
  const existing = new Set(listKbDocs().map((d) => d.file.toLowerCase()));
  let name = `${base}.md`;
  let i = 2;
  while (existing.has(name.toLowerCase())) {
    name = `${base}_${i}.md`;
    i += 1;
  }
  return name;
}

function bullets(items?: string[]): string {
  const list = (items ?? []).filter(Boolean);
  return list.length ? list.map((i) => `- ${i}`).join("\n") : "- (none recorded)";
}

function templateDraft(src: KbSource): KbDraft {
  const titleSeed =
    src.question?.split(/[.?!\n]/)[0]?.trim() ||
    src.resolution?.split(/[.?!\n]/)[0]?.trim() ||
    (src.domain ? `${src.domain} help` : "Support article");
  const title = titleSeed.replace(/\s+/g, " ").slice(0, 80);
  const content = [
    `# ${title}`,
    "",
    "## Issue",
    src.question?.trim() || "Customer reported an issue handled by support.",
    "",
    "## Resolution",
    src.resolution?.trim() || "See the steps below.",
    "",
    "## Key findings",
    bullets(src.findings),
    "",
    "## Steps to resolve",
    bullets(src.actions),
    src.notes ? `\n## Notes\n${src.notes.trim()}` : "",
    "",
    "_Draft generated from a resolved ticket. Review for accuracy before publishing._",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
  return {
    title,
    filename: uniqueFilename(slugify(title)),
    content,
    summary: src.resolution?.slice(0, 160) || title,
    source: "template",
  };
}

interface RawDraft {
  title?: string;
  filename?: string;
  content?: string;
  summary?: string;
}

function buildSystem(): string {
  return [
    GUARDRAILS_BLOCK,
    "",
    "You are a knowledge-base author for a customer-support team. From a RESOLVED",
    "support interaction, write ONE reusable help-center article that future",
    "customers and agents can follow. Generalize away customer-specific data",
    "(names, order numbers, emails) — never include PII. Use ONLY the facts",
    "provided; do not invent policies, numbers, or steps.",
    "",
    "Write clean GitHub-flavored Markdown with these sections:",
    "# <concise title>",
    "## Overview  (1-2 sentences on the problem)",
    "## Resolution steps  (numbered, actionable)",
    "## Notes / edge cases  (optional)",
    "",
    "Return STRICT JSON only, no prose, no code fences, shaped:",
    '{ "title": string, "filename": string (lowercase, words_with_underscores, ending .md),',
    '  "summary": string (<=160 chars), "content": string (the full markdown article) }',
  ].join("\n");
}

function buildUser(src: KbSource): string {
  return [
    src.domain ? `DOMAIN: ${src.domain}` : "",
    "",
    `CUSTOMER PROBLEM:\n${src.question?.trim() || "(not provided)"}`,
    "",
    `ENGINE RESOLUTION:\n${src.resolution?.trim() || "(not provided)"}`,
    "",
    `FINDINGS:\n${bullets(src.findings)}`,
    "",
    `ACTIONS TAKEN:\n${bullets(src.actions)}`,
    src.notes ? `\nADDITIONAL CONTEXT:\n${src.notes.trim()}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * Generate a KB article draft from a resolved interaction. Always returns a
 * usable draft (LLM when available, deterministic template otherwise).
 */
export async function generateKbArticle(src: KbSource, traceId = "kb-generate"): Promise<KbDraft> {
  if (availableProviders().length === 0) return templateDraft(src);

  try {
    const raw = await callLLM<RawDraft>({
      system: buildSystem(),
      user: buildUser(src),
      json: true,
      traceId,
      options: { temperature: 0.3, maxTokens: 900 },
    });
    const content = String(raw.content ?? "").trim();
    if (!content) return templateDraft(src);
    const title = String(raw.title ?? "").trim() || templateDraft(src).title;
    const base = raw.filename
      ? slugify(String(raw.filename).replace(/\.md$/i, ""))
      : slugify(title);
    return {
      title,
      filename: uniqueFilename(base),
      content,
      summary: String(raw.summary ?? "").trim() || title,
      source: "llm",
    };
  } catch (err) {
    log(traceId, "kb-generate", "LLM draft failed, using template", { error: String(err) });
    return templateDraft(src);
  }
}
